### ISSUE TITLE
question about Qat Driver config files

### ISSUE THREAD

**Issue by limingllmm** [01org/QAT_Engine#17]
Hi,
  I'm using openssl 1.1.0e and qat engine to do https things.  
    acceleration device : dh8920
   
  My application runs one process and 4 threads in the process. According to _“Copy the correct Intel® Quickassist Technology Driver config files”_ chapter in README, I choose multi_thread_optimized config files, but the performance is really bad,  TLS1.2 RSA2048-AES  got only 1400 CPS(requests per second),   but when switch to multi_process_optimized config files, the performance  goes up to 5500 CPS .

**Comment by stevelinsell** [comment]
Hi,

For the dh8920 the multi_thread_optimized and multi_process_optimized example driver config files are actually very similar.
The differences are as follows:
1) The multi_thread_optimized config file uses LimitDevAccess=0 whereas the multi_process_optimized file uses LimitDevAccess=1. The LimitDevAccess setting is useful only when running multiple dh8920 accelerators in a machine. It controls whether instances from multiple devices are visible to a particular process.
So for instance with 2 x dh8920 devices and using the example multi__thread_optimised files (LimitDevAccess=0) the process would be able to see 8 logical instances, 4 from each device. As NumOfProcesses is set only to 1, you would only be able to start 1 process that uses acceleration but it would be able to access all 8 instances across the 2 devices. 
The other case would be when using 2 x dh8920 devices and the example multi_process_optimised files (LimitDevAccess=1). In that case NumOfProcesses is set to 8 in each config file. That behaves differently and will allow 16 process to access acceleration. The first 8 processes will have 4 logical instances available, all 4 will be from the first dh8920 device. The next 8 processes will also have 4 logical instances available but all 4 will be from the second dh8920 device.
2) The NumOfProcesses setting is different by default, The multi_thread_optimized file is making an assumption that you only want to run 1 process that will access acceleration and restricting you to that. As mentioned in item 1 the multi_process_optimized file allows you to run 8 processes that use acceleration.

In your particular case I believe that item 1 above is not relevant as you only have 1 x dh8920 device. It will make no difference to your configuration as you will get 4 logical instances available which ever file you use. I think the key point is in item 2 above. For the multi_thread_optimized file only allowing 1 process to access acceleration is quite restrictive. I suspect that if you are accelerating an application such as nginx for example it may well fork during startup creating a master and child process. If the Intel QAT Engine is being started in the master process rather than the child then you will end up with 2 processes both with acceleration started. This will not work with the multi_thread_optimized config file. In that case the child process is probably failing to use acceleration and is dropping to use software instead. If that is the case you should be seeing some errors coming from stderr or in the kernel log.

My suggestion would be as follows:
As you are only using 1x  dh8920 device you are okay to keep using the multi_process_optimized config file if that is giving you the performance as desired (my understanding is that 5500 cps is the expected RSA performance for a dh8920 device).
If you do want to use the multi_thread_optimized config file then I would suggest changing the NumOfProcesses setting to either 2 or 4 processes and rerunning your tests and see if that allows you to reach the expected 5500 cps.

**Comment by limingllmm** [comment]
Hi， Steve
 thanks for your reply，
 it seems that NumOfProcesses has nothing to do with this issue。
 the reason is that some items in the multi_thread_optimized config file is wrong ？

>  [SHIM]
> NumberCyInstances = 4
> NumberDcInstances = 0
> NumProcesses = 1
> LimitDevAccess = 0
> 
> Cy0Name = "UserCY0"
> **Cy0Accelerator** = 0,1,2,3
> Cy0IsPolled = 1
> Cy0CoreAffinity = 0

**CyxAccelerator** should be **CyxAcceleratorNumber** ？ 
 after I modify it， the performance is fine now！

**Comment by stevelinsell** [comment]
Thankyou for diagnosing it, I didn't spot that!
I'll fix it in the baseline so other people are not affected by it.
I'll close this issue now as you are seeing the performance you expect.
