### ISSUE TITLE
unknown option -nostatic

### ISSUE THREAD

**Issue by GCM707** [01org/QAT_Engine#27]
Running into this error when running make under /QAT_Engine.
Right after it tries to run perl /openssl/util/mkerr.pl

**Comment by stevelinsell** [comment]
Hi @GCM707,

The error you are encountering is caused when you build against the OpenSSL master branch.
It was introduced by the following Openssl commit:

make error tables const and separate header file
https://github.com/openssl/openssl/commit/52df25cf2e656146cb3b206d8220124f0417d03f

The QAT Engine is written to build against the OpenSSL 1.1.0 branch, We specifically test against the OpenSSL 1.1.0f release.

Unfortunately the commit above in Master branch breaks backwards compatibility.
We plan to add a new configure option very shortly which will allow the QAT Engine to build against Master branch again although we would recommend you stick to building against the stable OpenSSL 1.1.0 release unless there is a feature you need in Master branch.

Hope that is helpful,

Steve.

**Comment by GCM707** [comment]
Thanks for the info. I’ve been trying to get this working in the latest beta version of vyos. Looking forward to your next update, I will see what else I can do in the mean time.

**Comment by stevelinsell** [comment]
Hi @GCM707,

I've just posted the latest QAT Engine release v0.5.26 that contains the fix for the nostatic bug you are seeing.
The specific commit that fixes it is:
Makefile Changes to accommodate latest mkerr.pl in OpenSSL
https://github.com/01org/QAT_Engine/commit/17a1808cdfa02afa6eed5d35c2027c1522a24203

Note: you'll need to run configure with the option:
--enable-qat_for_openssl_master
which will then configure the Makefile to use the required different options when calling mkerr.pl 

If that solves your problem then please close this issue, any issues then let me know.

Steve.

**Comment by GCM707** [comment]
it gets further. stops at this message:

In file included from e_qat.c:80:0:
e_qat.h:53:18: fatal error: cpa.h: No such file or directory
 # include "cpa.h"
                  ^
compilation terminated.

Unsure if that comes with something i should have already installed, im a bit new to this.

**Comment by stevelinsell** [comment]
Hi @GCM707,

Apologies for the slow reply.
The cpa.h header file is one of the QuickAssist API files. It is included with the QAT Driver source code. If you follow the installation instructions in the README.md file included with the QAT Engine it contains pointers on installing the QAT Driver and example QAT Engine configure options to point the QAT Engine build to where the QAT Driver source is so that it can find the Quickassist API header files. The configure option you need to use is:

  `--with-qat_dir=/path/to/qat_driver`

Ensure that the option is pointing to the correct folder level within the QAT Driver. For instance if you have installed the QAT Driver to /QAT and are using an Intel&reg; Communications Chipset 8925 to 8955 Series device then you would use the following setting:

 ` --with-qat_dir=/QAT/QAT1.6`

Kind Regards,

Steve.

**Comment by mindreader** [comment]
We've dealt with this issue, feel free to close this issue.
